version: '3'
services:

  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network

  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/node-firefox:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge