version: '3'
services:

  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network
    depends_on:
      - selenium-hub

  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/node-firefox:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network
    depends_on:
      - selenium-hub

  selenium-hub:
    container_name: selenium-hub:4.19.0
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-network
    command: java -jar selenium-server-standalone-4.19.0.jar -role hub

  selenium-node:
    image: openjdk:latest
    command: java -jar selenium-server-4.19.0.jar node --hub http://143.110.244.31:4444
    depends_on:
      - selenium-hub

networks:
  selenium-network:
    driver: bridge